# ==============================================================================
# 09c_chemont_model_validation.R
# Model validation via structure-defined substances as ground truth
#
# PURPOSE
# -------
# Structure-defined substances have a known ChemOnt class via ClassyFire
# (encoded in data/processed/rdf/substances_taxonomy_levels.ttl via wk:
# typed hierarchy properties).  This provides an internal ground truth: for
# each such substance, we know which ChemOnt class is correct at each level.
#
# By embedding the *names* of structure-defined substances and ranking ChemOnt
# classes by cosine similarity, we can measure how often each model places the
# correct class in the top-1, top-3, and top-5 positions — a standard
# information retrieval metric (Hit@k).
#
# This is a principled comparison that does not require external labelled data:
# the ground truth is derived from structure-based classification (ClassyFire),
# which is independent of the embedding models being evaluated.
#
# DATA PROVENANCE
# ---------------
# Input: data/processed/chemont_ground_truth.csv
#   Generated by bash/chemont_broader_substance.sh via SPARQL against
#   data/processed/rdf/substances_taxonomy_levels.ttl.
#   Columns: inchikey, substance, substance_name, chemont_label (direct parent
#   class via skos:broader), subclass, class, superclass, kingdom (typed
#   hierarchy levels from wk: properties).
#   Hierarchy specificity: chemont_label > subclass > class > superclass > kingdom.
#
# METHODOLOGY
# -----------
# ## Established frameworks used as anchors
#
# | Framework | Role in methodology |
# |---|---|
# | **ChemOnt 2.1 / ClassyFire** (Djoumbou Feunang et al. 2016) | Ground-truth chemical taxonomy; defines the hierarchy levels |
# | **Hit@k / MRR** (standard IR metrics) | Retrieval performance at each taxonomy level |
#
# ## Own methodological additions
#
# | Choice | Justification |
# |---|---|
# | Per-level Hit@k (subclass/class/superclass/kingdom) | Each taxonomy level has different discriminative power; a single lenient metric hides where models fail in the hierarchy |
# | Weighted lenient MRR weights 1.00/0.75/0.50/0.25/0.10 | Reflect decreasing specificity moving up the ChemOnt hierarchy; weights are ordinal, not empirically calibrated |
#
# INTERPRETATION
# --------------
# 1. Strict Hit@k (direct parent): how often the model retrieves the exact
#    ClassyFire class in the top k — the hardest and most meaningful metric.
# 2. Per-level Hit@k: performance at each hierarchy level; higher levels
#    (kingdom, superclass) should always be easier than lower ones (subclass).
#    If a model scores better at kingdom than at subclass, that is expected.
#    If it scores poorly even at kingdom, the embedding is uninformative.
# 3. mrr_weighted: a single summary that rewards specificity — a kingdom-level
#    match at rank 1 is worth less than a subclass-level match at rank 2.
#    Models should be ranked by mrr_weighted, not mrr_strict alone.
#
# OUTPUTS
# -------
# output/figures/Analysis_9c_model_validation.pdf
# output/tables/Analysis_9c_model_validation.csv
# ==============================================================================

library(dplyr)
library(ggplot2)
library(here)
library(reticulate)
library(purrr)
library(readr)
library(tidyr)
library(stringr)
library(patchwork)

reticulate::py_require("sentence-transformers")


# ------------------------------------------------------------------------------
# Configuration
# ------------------------------------------------------------------------------

models <- list(
  list(id = "miniLM",  name = "all-MiniLM-L6-v2"),
  list(id = "mpnet",   name = "all-mpnet-base-v2"),
  list(id = "scibert", name = "allenai/scibert_scivocab_uncased"),
  list(id = "biobert", name = "dmis-lab/biobert-v1.1")
)

dir.create(here("data", "cache", "embeddings"), showWarnings = FALSE, recursive = TRUE)

# ------------------------------------------------------------------------------
# Step 1: Load ground truth from SPARQL output
# Run bash/chemont_broader_substance.sh first to generate this file.
# See DATA PROVENANCE in the header for column descriptions.
# ------------------------------------------------------------------------------
system("bash bash/chemont_broader_substance.sh")


ground_truth_file <- here("data", "processed", "chemont_ground_truth.csv")

if (!file.exists(ground_truth_file)) {
  stop(paste(
    "Ground truth file not found:", ground_truth_file,
    "\nRun bash/chemont_broader_substance.sh first."
  ))
}

# Columns: inchikey, substance, substance_name, chemont_label (direct parent class),
#          subclass, class, superclass, kingdom (typed hierarchy levels from wk: properties).
ground_truth <- read_csv(ground_truth_file, show_col_types = FALSE) |>
  filter(!is.na(inchikey), !is.na(chemont_label))

message(sprintf("Ground truth: %d substance-class pairs loaded",
                nrow(ground_truth)))

# ------------------------------------------------------------------------------
# Step 2: Join with substance names
# ------------------------------------------------------------------------------

all_substances <- readRDS(here("data", "processed", "all_substances_classified.rds"))

validation_set <- all_substances |>
  filter(!is.na(inchikey)) |>
  distinct(substance_name, inchikey) |>
  inner_join(
    ground_truth |> select(-any_of("substance_name")),
    by = "inchikey",
    relationship = "many-to-many"
  ) |>
  filter(!is.na(substance_name), nzchar(substance_name))

message(sprintf("Validation set: %d (substance_name, correct_chemont_label) pairs",
                nrow(validation_set)))

# ------------------------------------------------------------------------------
# Step 3: Load ChemOnt labels and helper functions
# ------------------------------------------------------------------------------

chemont     <- readRDS(here("data", "source", "ChemOnt_2_1.rds"))
chemont$substance_name <- chemont$label
chemont <- chemont |> select("substance", "substance_name")

normalize <- function(x) x / sqrt(rowSums(x^2))

embed_with_model <- function(texts, model_name, cache_file, batch_size = 32L) {
  if (file.exists(cache_file)) {
    message(sprintf("  Loading cached embeddings from %s", basename(cache_file)))
    return(readRDS(cache_file))
  }
  message(sprintf("  Embedding %d texts with %s", length(texts), model_name))
  Sys.setenv(TOKENIZERS_PARALLELISM = "false")

  # Write texts to a temp file (one per line, using \x00 as separator to
  # avoid newline issues in substance names)
  texts_file <- tempfile(fileext = ".txt")
  npy_file   <- tempfile(fileext = ".npy")
  py_file    <- tempfile(fileext = ".py")

  # Collapse embedded newlines so each text occupies exactly one line
  writeLines(gsub("[\r\n]+", " ", texts), texts_file)

  py_script <- paste0('
import os
import numpy as np
os.environ["TOKENIZERS_PARALLELISM"] = "false"
from sentence_transformers import SentenceTransformer

with open("', texts_file, '", "r", encoding="utf-8") as f:
    texts = [line.rstrip("\\n") for line in f]

model = SentenceTransformer("', model_name, '")
emb = model.encode(texts, batch_size=', as.integer(batch_size), ', show_progress_bar=True, convert_to_numpy=True)
np.save("', npy_file, '", emb)
print(f"Saved embeddings: {emb.shape}", flush=True)
')
  writeLines(py_script, py_file)

  python <- reticulate::py_exe()
  ret    <- system2(python, py_file, stdout = "", stderr = "")
  if (ret != 0L) stop(sprintf("Python embedding failed (exit code %d) for model %s",
                               ret, model_name))

  np  <- reticulate::import("numpy")
  emb <- np$load(npy_file)
  file.remove(texts_file, npy_file, py_file)
  saveRDS(emb, cache_file)
  emb
}

# ------------------------------------------------------------------------------
# Step 4: Evaluate each model via Hit@k and MRR
# ------------------------------------------------------------------------------

evaluate_model <- function(model_id, model_name) {
  message(sprintf("\n=== Evaluating: %s (%s) ===", model_id, model_name))

  emb_substances <- embed_with_model(
    texts      = validation_set$substance_name,
    model_name = model_name,
    cache_file = here("data", "cache", "embeddings",
                      sprintf("%s_validation.rds", model_id))
  )

  emb_chemont <- embed_with_model(
    texts      = chemont$substance_name,
    model_name = model_name,
    cache_file = here("data", "cache", "embeddings",
                      sprintf("%s_chemont.rds", model_id))
  )

  sub_norm <- normalize(as.matrix(emb_substances))
  che_norm <- normalize(as.matrix(emb_chemont))
  sim      <- sub_norm %*% t(che_norm)

  # Helper: rank of a single label per substance (NA if label missing or not in ChemOnt)
  level_ranks <- function(labels) {
    idxs <- match(labels, chemont$substance_name)
    map_int(seq_len(nrow(sim)), function(i) {
      if (is.na(idxs[i])) return(NA_integer_)
      rank(-sim[i, ], ties.method = "min")[idxs[i]]
    })
  }

  ranks_strict <- level_ranks(validation_set$chemont_label)
  ranks_sub    <- level_ranks(validation_set$subclass)
  ranks_cls    <- level_ranks(validation_set$class)
  ranks_sup    <- level_ranks(validation_set$superclass)
  ranks_kin    <- level_ranks(validation_set$kingdom)

  # Weighted lenient MRR: rewards specificity.
  # Own addition: weights 1.00/0.75/0.50/0.25/0.10 reflect decreasing
  # specificity moving up the ChemOnt hierarchy; ordinal, not empirically calibrated.
  mrr_weighted_vec <- pmax(
    ifelse(!is.na(ranks_strict), 1.00 / ranks_strict, 0),
    ifelse(!is.na(ranks_sub),    0.75 / ranks_sub,    0),
    ifelse(!is.na(ranks_cls),    0.50 / ranks_cls,    0),
    ifelse(!is.na(ranks_sup),    0.25 / ranks_sup,    0),
    ifelse(!is.na(ranks_kin),    0.10 / ranks_kin,    0)
  )

  tibble(
    model_id       = model_id,
    model_name     = model_name,
    # Strict metrics (direct parent only)
    hit_at_1       = mean(ranks_strict == 1L,  na.rm = TRUE),
    hit_at_3       = mean(ranks_strict <= 3L,  na.rm = TRUE),
    hit_at_5       = mean(ranks_strict <= 5L,  na.rm = TRUE),
    hit_at_10      = mean(ranks_strict <= 10L, na.rm = TRUE),
    mrr            = mean(1 / ranks_strict,    na.rm = TRUE),
    # Per-level Hit@k (Own addition: hierarchy-aware granularity)
    hit_at_1_sub   = mean(ranks_sub == 1L,  na.rm = TRUE),
    hit_at_3_sub   = mean(ranks_sub <= 3L,  na.rm = TRUE),
    hit_at_1_cls   = mean(ranks_cls == 1L,  na.rm = TRUE),
    hit_at_3_cls   = mean(ranks_cls <= 3L,  na.rm = TRUE),
    hit_at_1_sup   = mean(ranks_sup == 1L,  na.rm = TRUE),
    hit_at_3_sup   = mean(ranks_sup <= 3L,  na.rm = TRUE),
    hit_at_1_kin   = mean(ranks_kin == 1L,  na.rm = TRUE),
    hit_at_3_kin   = mean(ranks_kin <= 3L,  na.rm = TRUE),
    # Weighted lenient MRR (Own addition: penalises high-level matches)
    mrr_weighted   = mean(mrr_weighted_vec, na.rm = TRUE),
    n_eval         = sum(!is.na(ranks_strict))
  )
}

py_gc <- reticulate::import("gc")
metrics <- map_dfr(models, function(m) {
  result <- evaluate_model(m$id, m$name)
  py_gc$collect()
  result
})

print(metrics)

# Columns (Analysis_9c_model_validation.csv):
#   model_id       — short model identifier
#   hit_at_1/3/5/10 — strict: fraction where direct parent class is in top k
#   mrr            — strict mean reciprocal rank (higher = better)
#   hit_at_1_sub/cls/sup/kin — Hit@1 at subclass/class/superclass/kingdom level
#   hit_at_3_sub/cls/sup/kin — Hit@3 at each level
#   mrr_weighted   — weighted lenient MRR (weights: direct=1.0, sub=0.75, class=0.50, sup=0.25, kingdom=0.10)
#   n_eval         — number of substances with direct parent found in ChemOnt
write_csv(metrics,
          here("output", "tables", "Analysis_9c_model_validation.csv"))

# ------------------------------------------------------------------------------
# Plot: three panels — strict Hit@k, per-level Hit@1, MRR comparison
# INTENT: show where models succeed or fail across the ChemOnt hierarchy
# ------------------------------------------------------------------------------

# Panel 1: strict Hit@k (direct parent class)
strict_long <- metrics |>
  select(model_id, hit_at_1, hit_at_3, hit_at_5, hit_at_10) |>
  pivot_longer(-model_id, names_to = "metric", values_to = "value") |>
  mutate(metric = factor(metric,
                         levels = c("hit_at_1", "hit_at_3", "hit_at_5", "hit_at_10"),
                         labels = c("Hit@1", "Hit@3", "Hit@5", "Hit@10")))

p_strict <- ggplot(strict_long, aes(x = metric, y = value, fill = model_id)) +
  geom_col(position = "dodge", width = 0.7) +
  scale_y_continuous(labels = scales::percent_format(), limits = c(0, 1)) +
  scale_fill_brewer(palette = "Set2", name = "Model") +
  theme_minimal(base_size = 12) +
  labs(
    title    = "Strict Hit@k (direct ChemOnt parent)",
    subtitle = "Ground truth: structure-defined substances with known ClassyFire class",
    x        = NULL,
    y        = "Fraction correct"
  ) +
  theme(plot.subtitle = element_text(colour = "grey40"))

# Panel 2: Hit@1 per hierarchy level (Own addition: hierarchy-aware granularity)
# Level order: subclass (most specific) → kingdom (least specific)
levels_long <- metrics |>
  select(model_id,
         subclass   = hit_at_1_sub,
         class      = hit_at_1_cls,
         superclass = hit_at_1_sup,
         kingdom    = hit_at_1_kin) |>
  pivot_longer(-model_id, names_to = "level", values_to = "hit_at_1") |>
  mutate(level = factor(level,
                        levels = c("subclass", "class", "superclass", "kingdom")))

p_levels <- ggplot(levels_long, aes(x = level, y = hit_at_1, fill = model_id)) +
  geom_col(position = "dodge", width = 0.7) +
  scale_y_continuous(labels = scales::percent_format(), limits = c(0, 1)) +
  scale_fill_brewer(palette = "Set2", name = "Model") +
  theme_minimal(base_size = 12) +
  labs(
    title    = "Hit@1 per taxonomy level (most → least specific)",
    subtitle = "Own addition: each level evaluated independently; higher levels should be easier",
    x        = NULL,
    y        = "Hit@1"
  ) +
  theme(plot.subtitle = element_text(colour = "grey40"))

# Panel 3: strict MRR vs weighted lenient MRR
mrr_long <- metrics |>
  select(model_id, mrr_strict = mrr, mrr_weighted) |>
  pivot_longer(-model_id, names_to = "type", values_to = "value") |>
  mutate(type = factor(type,
                       levels = c("mrr_strict", "mrr_weighted"),
                       labels = c("Strict MRR", "Weighted MRR")))

p_mrr <- ggplot(mrr_long, aes(x = reorder(model_id, value), y = value, fill = type)) +
  geom_col(position = "dodge", width = 0.6) +
  geom_text(aes(label = round(value, 3)),
            position = position_dodge(width = 0.6),
            hjust = -0.1, size = 3.5) +
  scale_y_continuous(expand = expansion(mult = c(0, 0.25))) +
  scale_fill_brewer(palette = "Paired", name = NULL) +
  coord_flip() +
  theme_minimal(base_size = 12) +
  labs(
    title    = "MRR: strict vs weighted lenient",
    subtitle = "Weighted MRR weights: direct=1.0, subclass=0.75, class=0.50, superclass=0.25, kingdom=0.10",
    x        = NULL,
    y        = "MRR"
  ) +
  theme(plot.subtitle = element_text(colour = "grey40"))

p_val <- (p_strict / p_levels / p_mrr) +
  plot_layout(heights = c(1.5, 1.5, 1))

ggsave(p_val,
       filename = here("output", "figures", "Analysis_9c_model_validation.pdf"),
       device = "pdf", height = 35, width = 30, units = "cm")

message("09c_chemont_model_validation.R: validation completed")
